modLoader="javafml"
license="MIT"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/zehmaria/createpickywheels/issues"
displayURL="https://github.com/zehmaria/createpickywheels"
logoFile="logo.png"

[[mods]]
    modId="createpickywheels"
    version="${file.jarVersion}"
    displayName="Create Picky Wheels"
	authors="zeh_maria"
    description="Changing Waterwheels generation requirements: Large body of water + River Biomes."

[[dependencies.createpickywheels]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createpickywheels]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,0.6.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createpickywheels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
